# Site settings
title: pebble {code}
email: hello@pebblecode.com
description: > # this means to ignore newlines until "baseurl:"
  pebble {code} - Technology Innovation Consultancy - Design Thinking, Rapid Prototyping and Agile Software Development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pebblecode.com" # the base hostname & protocol for your site
twitter: pebblecode
github:  pebblecode
vimeo:  pebblecode


# Build settings
markdown: kramdown
redirects: yes
sass:
    style: :compressed
permalink: "/blog/:title"


# Pagination
paginate: 8
paginate_path: "/blog/:num"

#tag blog posts for analytics
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      analytics_category: "blog"

